 steps:
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args:
       - -c
       - |
         echo "Upgrading node pool..."
         gcloud container clusters upgrade my-cluster \
           --node-pool=pool-1 \
           --cluster=my-cluster \
           --region=us-central1 \
           --project=$PROJECT_ID \
           --quiet

  #  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #    entrypoint: bash
  #    args:
  #      - -c
  #      - |
  #        echo "Checking node status..."
  #        gcloud container clusters describe my-cluster --region=us-central1 \
  #        --format="value(currentMasterVersion)"
  #        kubectl get nodes

  #  - name: 'gcr.io/cloud-builders/gcloud'
  #    args: ["echo", "NodePort change detected!"]

   - name: 'gcr.io/cloud-builders/kubectl'
     args:
       - apply
       - -f
       - k8s/service.yaml

 timeout: 600s


