steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Upgrading node pool..."
      gcloud container clusters upgrade my-cluster \
        --node-pool=default-pool \
        --cluster=my-cluster \
        --region=us-central1 \
        --project=$PROJECT_ID \
        --quiet
