steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Upgrading node pool..."
      gcloud container clusters upgrade my-cluster \
        --node-pool=default-pool \
        --cluster=my-cluster \
        --region=us-central1 \
        --project=$PROJECT_ID \
        --quiet

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Checking node status..."
      gcloud container clusters describe my-cluster --region=us-central1 \
      --format="value(currentMasterVersion)"
      kubectl get nodes
