steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
  - -c
  - |
    echo "✅ GKE upgrade detected!"
    gcloud container clusters describe my-cluster --zone us-central1-a
